apiVersion: metal.ironcore.dev/v1alpha4
kind: SwitchConfig
metadata:
  name: spines-config
  namespace: ironcore
  labels:
    metal.ironcore.dev/type: "spine"
spec:
  switches:
    matchLabels:
      metal.ironcore.dev/type: "spine"
  portsDefaults:
    lanes: 4
    mtu: 9100
    ipv4MaskLength: 30
    ipv6Prefix: 112
    state: "up"
    fec: "rs"
  ipam:
    addressFamily:
      ipv4: true
      ipv6: true
    carrierSubnets:
      labelSelector:
        matchLabels:
          ipam.metal.ironcore.dev/object-purpose: "switch-carrier"
    loopbackSubnets:
      labelSelector:
        matchLabels:
          ipam.metal.ironcore.dev/object-purpose: "switch-loopbacks"
    southSubnets:
      labelSelector:
        matchLabels:
          ipam.metal.ironcore.dev/object-purpose: "south-subnet"
      fieldSelector:
        labelKey: "ipam.metal.ironcore.dev/object-owner"
        fieldRef:
          fieldPath: "metadata.name"
    loopbackAddresses:
      labelSelector:
        matchLabels:
          ipam.metal.ironcore.dev/object-purpose: "loopback"
      fieldSelector:
        labelKey: "ipam.metal.ironcore.dev/object-owner"
        fieldRef:
          fieldPath: "metadata.name"
