linters:
  enable-all: false
  enable:
    - errorlint
    - funlen
    - gocyclo
    - gofmt
    - goheader
    - goimports
    - gosimple
    - govet
    - ifshort
    - importas
    - lll
    - nestif
    - misspell
    - staticcheck
    - stylecheck
    - unused
    - whitespace

linters-settings:
  errorlint:
    # Check whether fmt.Errorf uses the %w verb for formatting errors. See the readme for caveats
    errorf: true
    # Check for plain type assertions and type switches
    asserts: true
    # Check for plain error comparisons
    comparison: true
  
  funlen:
    lines: 100
    statements: 40

  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 15

  goheader:
   template: |-
    Copyright 2021 T-Systems International GmbH, SAP SE or an SAP affiliate company. All right reserved

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/onmetal/*

  gosimple:
    # Select the Go version to target. The default is '1.13'.
    go: "1.17"
    # https://staticcheck.io/docs/options#checks
    checks: ["all"]

  govet:
    go: "1.17"
    # report about shadowed variables
    check-shadowing: true
    # enable or disable analyzers by name
    # run `go tool vet help` to see all analyzers
    enable:
      - assign
      - atomic
      - bools
      - copylocks
      - loopclosure
      - lostcancel
      - nilfunc
      - nilness
      - shadow
      - unreachable
      - unsafeptr
      - unusedresult
    enable-all: false
  
  ifshort:
    # Maximum length of variable declaration measured in number of lines, after which linter won't suggest using short syntax.
    # Has higher priority than max-decl-chars.
    max-decl-lines: 1
    # Maximum length of variable declaration measured in number of characters, after which linter won't suggest using short syntax.
    max-decl-chars: 30
  
  importas:
    # if set to `true`, force to use alias.
    no-unaliased: true
    # List of aliases
    alias:
      # using `servingv1` alias for `knative.dev/serving/pkg/apis/serving/v1` package
      - pkg: github.com/onmetal/switch-operator/api/v1alpha1
        alias: switchv1alpha1
  
  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 160
    # tab width in spaces. Default to 1.
    tab-width: 4
  
  nestif:
    # minimal complexity of if statements to report, 5 by default
    min-complexity: 5
  
  misspell:
    locale: US

  staticcheck:
    go: "1.17"
    checks: [ "all" ]

  stylecheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.17"
    # https://staticcheck.io/docs/options#checks
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
  
  unused:
    # Select the Go version to target. The default is '1.13'.
    go: "1.17"

  whitespace:
    multi-if: false # Enforces newlines (or comments) after every multi-line if statement
    multi-func: false # Enforces newlines (or comments) after every multi-line function signature

issues:
  exclude-rules:
    - linters:
        - lll
      source: "^//\\+kubebuilder"

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: true