run:
  timeout: 5m

linters:
  enable:
    - megacheck
    - govet
    - cyclop
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - funlen
    - gci
    - gocognit
    - nestif
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomoddirectives
    - gosec
    - gosimple
    - govet
    - ineffassign
    - durationcheck
    - errname
    - lll
    - misspell
    - staticcheck
    - stylecheck
    - unparam
    - unused
    - whitespace
    - asciicheck
    - bodyclose
    - dogsled
    - exportloopref
    - forcetypeassert
    - godot
    - goerr113
    - goprintffuncname
    - importas
    - nakedret
    - nilerr
    - noctx
    - prealloc
    - predeclared
    - rowserrcheck
    - unconvert
    - wastedassign

severity:
  default-severity: error

linters-settings:
  revive:
    severity: error
    rules:
      - name: exported
      - name: if-return
        disabled: true

issues:
  exclude-rules:
    - path: _gen\.go
      linters:
        - typecheck
