run:
  concurrency: 4
  allow-parallel-runners: true
  timeout: 5m

linters:
  # temporarily disabled linters
  disable:
    - funlen
    - goconst
    - lll

  enable:
    - asciicheck
    - dogsled
    - durationcheck
    - dupl
    - errcheck
    - forcetypeassert
    - gocyclo
    - godot
    - gofmt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - nakedret
    - paralleltest
    - prealloc
    - predeclared
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

severity:
  default-severity: error

linters-settings:
  revive:
    severity: error
    rules:
      - name: exported
      - name: if-return
        disabled: true

issues:
  exclude-rules:
    - path: _gen\.go
      linters:
        - typecheck
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - lll
        - goconst
    - path: track_controller.go
      linters:
        - dupl
    - path: constants
      linters:
        - lll
    - linters:
        - lll
      source: "^// [+]kubebuilder"
