run:
  timeout: 5m

linters:
  enable:
    - ineffassign
    - misspell
    - goimports
    - govet
    - gofmt
    - goimports
    - godot
    - predeclared
    - unconvert
    - whitespace
    - unused
    - unconvert
    - dogsled
    - misspell
    - paralleltest
    - prealloc
    - importas
    - asciicheck
    - stylecheck
    - durationcheck
    - unparam
    - goprintffuncname
    - forcetypeassert

severity:
  default-severity: error

linters-settings:
  revive:
    severity: error
    rules:
      - name: exported
      - name: if-return
        disabled: true

issues:
  exclude-rules:
    - path: _gen\.go
      linters:
        - typecheck
