apiVersion: v1
data:
  controller_manager_config.yaml: |
    apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
    kind: ControllerManagerConfig
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: 127.0.0.1:8080
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: fd5dceca.onmetal.de
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-manager-config"
  namespace: {{ .Values.namespace }}