apiVersion: {{ .Values.crd.aggregate.group }}/v1alpha1
kind: {{ .Values.crd.aggregate.kind }}
metadata:
  name: default
spec:
  aggregates:
    - sourcePath: blocks.blocks[*]
      targetPath: blocks.count
      aggregate: count
    - sourcePath: blocks.blocks[*].size
      targetPath: blocks.capacity
      aggregate: sum
    - sourcePath: cpus.cpus[*]
      targetPath: cpus.sockets
      aggregate: count
    - sourcePath: cpus.cpus[*].cores
      targetPath: cpus.cores
      aggregate: sum
    - sourcePath: cpus.cpus[*].siblings
      targetPath: cpus.threads
      aggregate: sum
    - sourcePath: nics.nics[*]
      targetPath: nics.count
      aggregate: count