apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-controller-manager-metrics
  labels:
    control-plane: {{ include "chart.fullname" . }}-controller-manager
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.metrics.type }}
  ports:
    - name: https
      port: {{ .Values.service.metrics.port }}
      targetPort: https
  selector:
    control-plane: controller-manager
    {{- include "chart.selectorLabels" . | nindent 4 }}