# permissions for end users to view switchassignments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Values.namespace }}-{{ .Values.crd.switchAssignment.singular }}-viewer-role"
rules:
- apiGroups:
  - {{ .Values.crd.switchAssignment.group }}
  resources:
  - {{ .Values.crd.switchAssignment.plural }}
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - {{ .Values.crd.switchAssignment.group }}
  resources:
  - {{ .Values.crd.switchAssignment.plural }}/status
  verbs:
  - get
