# permissions for end users to edit switchassignments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Values.namespace }}-{{ .Values.crd.switchAssignment.singular }}-editor-role"
rules:
- apiGroups:
  - {{ .Values.crd.switchAssignment.group }}
  resources:
  - {{ .Values.crd.switchAssignment.plural }}
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - {{ .Values.crd.switchAssignment.group }}
  resources:
  - {{ .Values.crd.switchAssignment.plural }}/status
  verbs:
  - get
