# permissions for end users to view switches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Chart.Name }}-viewer-role"
rules:
- apiGroups:
  - {{ .Values.crd.switch.group }}
  resources:
  - {{ .Values.crd.switch.plural }}
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - {{ .Values.crd.switch.group }}
  resources:
  - {{ .Values.crd.switch.plural }}/status
  verbs:
  - get
