apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-webhook-service
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.webhook.type }}
  ports:
    - port: {{ .Values.service.webhook.port }}
      targetPort: 9443
  selector:
    control-plane: controller-manager
  {{- include "chart.selectorLabels" . | nindent 4 }}