/*
Copyright (c) 2023 T-Systems International GmbH, SAP SE or an SAP affiliate company. All right reserved

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha4

// AddressFamiliesMapApplyConfiguration represents an declarative configuration of the AddressFamiliesMap type for use
// with apply.
type AddressFamiliesMapApplyConfiguration struct {
	IPv4 *bool `json:"ipv4,omitempty"`
	IPv6 *bool `json:"ipv6,omitempty"`
}

// AddressFamiliesMapApplyConfiguration constructs an declarative configuration of the AddressFamiliesMap type for use with
// apply.
func AddressFamiliesMap() *AddressFamiliesMapApplyConfiguration {
	return &AddressFamiliesMapApplyConfiguration{}
}

// WithIPv4 sets the IPv4 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPv4 field is set to the value of the last call.
func (b *AddressFamiliesMapApplyConfiguration) WithIPv4(value bool) *AddressFamiliesMapApplyConfiguration {
	b.IPv4 = &value
	return b
}

// WithIPv6 sets the IPv6 field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPv6 field is set to the value of the last call.
func (b *AddressFamiliesMapApplyConfiguration) WithIPv6(value bool) *AddressFamiliesMapApplyConfiguration {
	b.IPv6 = &value
	return b
}
