/*
Copyright (c) 2023 T-Systems International GmbH, SAP SE or an SAP affiliate company. All right reserved

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha4

// PCIDeviceDescriptionSpecApplyConfiguration represents an declarative configuration of the PCIDeviceDescriptionSpec type for use
// with apply.
type PCIDeviceDescriptionSpecApplyConfiguration struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// PCIDeviceDescriptionSpecApplyConfiguration constructs an declarative configuration of the PCIDeviceDescriptionSpec type for use with
// apply.
func PCIDeviceDescriptionSpec() *PCIDeviceDescriptionSpecApplyConfiguration {
	return &PCIDeviceDescriptionSpecApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *PCIDeviceDescriptionSpecApplyConfiguration) WithID(value string) *PCIDeviceDescriptionSpecApplyConfiguration {
	b.ID = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PCIDeviceDescriptionSpecApplyConfiguration) WithName(value string) *PCIDeviceDescriptionSpecApplyConfiguration {
	b.Name = &value
	return b
}
