// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/ironcore-dev/metal/api/v1alpha1"
)

// MachineClaimNetworkInterfaceApplyConfiguration represents an declarative configuration of the MachineClaimNetworkInterface type for use
// with apply.
type MachineClaimNetworkInterfaceApplyConfiguration struct {
	Name   *string          `json:"name,omitempty"`
	Prefix *v1alpha1.Prefix `json:"prefix,omitempty"`
}

// MachineClaimNetworkInterfaceApplyConfiguration constructs an declarative configuration of the MachineClaimNetworkInterface type for use with
// apply.
func MachineClaimNetworkInterface() *MachineClaimNetworkInterfaceApplyConfiguration {
	return &MachineClaimNetworkInterfaceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *MachineClaimNetworkInterfaceApplyConfiguration) WithName(value string) *MachineClaimNetworkInterfaceApplyConfiguration {
	b.Name = &value
	return b
}

// WithPrefix sets the Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefix field is set to the value of the last call.
func (b *MachineClaimNetworkInterfaceApplyConfiguration) WithPrefix(value v1alpha1.Prefix) *MachineClaimNetworkInterfaceApplyConfiguration {
	b.Prefix = &value
	return b
}
