// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// OOBSecretStatusApplyConfiguration represents an declarative configuration of the OOBSecretStatus type for use
// with apply.
type OOBSecretStatusApplyConfiguration struct {
	Conditions []v1.Condition `json:"conditions,omitempty"`
}

// OOBSecretStatusApplyConfiguration constructs an declarative configuration of the OOBSecretStatus type for use with
// apply.
func OOBSecretStatus() *OOBSecretStatusApplyConfiguration {
	return &OOBSecretStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *OOBSecretStatusApplyConfiguration) WithConditions(values ...v1.Condition) *OOBSecretStatusApplyConfiguration {
	for i := range values {
		b.Conditions = append(b.Conditions, values[i])
	}
	return b
}
