
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-switch-onmetal-de-v1alpha1-switch
  failurePolicy: Fail
  name: mswitch.kb.io
  rules:
  - apiGroups:
    - switch.onmetal.de
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - switches
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-switch-onmetal-de-v1alpha1-switchassignment
  failurePolicy: Fail
  name: mswitchassignment.kb.io
  rules:
  - apiGroups:
    - switch.onmetal.de
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    resources:
    - switchassignments
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-switch-onmetal-de-v1alpha1-switch
  failurePolicy: Fail
  name: vswitch.kb.io
  rules:
  - apiGroups:
    - switch.onmetal.de
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - switches
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-switch-onmetal-de-v1alpha1-switchassignment
  failurePolicy: Fail
  name: vswitchassignment.kb.io
  rules:
  - apiGroups:
    - switch.onmetal.de
    apiVersions:
    - v1alpha1
    operations:
    - UPDATE
    resources:
    - switchassignments
  sideEffects: None
