apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: metal-api-system

namePrefix: metal-api-exploitation-

bases:
  - ../deployment
  - ../rbac
  - ../service

transformers:
    - labels.yaml