// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha4

import (
	v1 "k8s.io/api/core/v1"
)

// FieldSelectorSpecApplyConfiguration represents an declarative configuration of the FieldSelectorSpec type for use
// with apply.
type FieldSelectorSpecApplyConfiguration struct {
	LabelKey *string                 `json:"labelKey,omitempty"`
	FieldRef *v1.ObjectFieldSelector `json:"fieldRef,omitempty"`
}

// FieldSelectorSpecApplyConfiguration constructs an declarative configuration of the FieldSelectorSpec type for use with
// apply.
func FieldSelectorSpec() *FieldSelectorSpecApplyConfiguration {
	return &FieldSelectorSpecApplyConfiguration{}
}

// WithLabelKey sets the LabelKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LabelKey field is set to the value of the last call.
func (b *FieldSelectorSpecApplyConfiguration) WithLabelKey(value string) *FieldSelectorSpecApplyConfiguration {
	b.LabelKey = &value
	return b
}

// WithFieldRef sets the FieldRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FieldRef field is set to the value of the last call.
func (b *FieldSelectorSpecApplyConfiguration) WithFieldRef(value v1.ObjectFieldSelector) *FieldSelectorSpecApplyConfiguration {
	b.FieldRef = &value
	return b
}
