// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha4

// HostSpecApplyConfiguration represents an declarative configuration of the HostSpec type for use
// with apply.
type HostSpecApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
}

// HostSpecApplyConfiguration constructs an declarative configuration of the HostSpec type for use with
// apply.
func HostSpec() *HostSpecApplyConfiguration {
	return &HostSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *HostSpecApplyConfiguration) WithName(value string) *HostSpecApplyConfiguration {
	b.Name = &value
	return b
}
