// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha4

// InternalApplyConfiguration represents an declarative configuration of the Internal type for use
// with apply.
type InternalApplyConfiguration struct {
	Name  *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
}

// InternalApplyConfiguration constructs an declarative configuration of the Internal type for use with
// apply.
func Internal() *InternalApplyConfiguration {
	return &InternalApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *InternalApplyConfiguration) WithName(value string) *InternalApplyConfiguration {
	b.Name = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *InternalApplyConfiguration) WithValue(value string) *InternalApplyConfiguration {
	b.Value = &value
	return b
}
