// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha4

// IPMISpecApplyConfiguration represents an declarative configuration of the IPMISpec type for use
// with apply.
type IPMISpecApplyConfiguration struct {
	IPAddress  *string `json:"ipAddress,omitempty"`
	MACAddress *string `json:"macAddress,omitempty"`
}

// IPMISpecApplyConfiguration constructs an declarative configuration of the IPMISpec type for use with
// apply.
func IPMISpec() *IPMISpecApplyConfiguration {
	return &IPMISpecApplyConfiguration{}
}

// WithIPAddress sets the IPAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPAddress field is set to the value of the last call.
func (b *IPMISpecApplyConfiguration) WithIPAddress(value string) *IPMISpecApplyConfiguration {
	b.IPAddress = &value
	return b
}

// WithMACAddress sets the MACAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MACAddress field is set to the value of the last call.
func (b *IPMISpecApplyConfiguration) WithMACAddress(value string) *IPMISpecApplyConfiguration {
	b.MACAddress = &value
	return b
}
