// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha4

// NDPSpecApplyConfiguration represents an declarative configuration of the NDPSpec type for use
// with apply.
type NDPSpecApplyConfiguration struct {
	IPAddress  *string `json:"ipAddress,omitempty"`
	MACAddress *string `json:"macAddress,omitempty"`
	State      *string `json:"state,omitempty"`
}

// NDPSpecApplyConfiguration constructs an declarative configuration of the NDPSpec type for use with
// apply.
func NDPSpec() *NDPSpecApplyConfiguration {
	return &NDPSpecApplyConfiguration{}
}

// WithIPAddress sets the IPAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPAddress field is set to the value of the last call.
func (b *NDPSpecApplyConfiguration) WithIPAddress(value string) *NDPSpecApplyConfiguration {
	b.IPAddress = &value
	return b
}

// WithMACAddress sets the MACAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MACAddress field is set to the value of the last call.
func (b *NDPSpecApplyConfiguration) WithMACAddress(value string) *NDPSpecApplyConfiguration {
	b.MACAddress = &value
	return b
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *NDPSpecApplyConfiguration) WithState(value string) *NDPSpecApplyConfiguration {
	b.State = &value
	return b
}
