// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha4

// PCIDeviceDescriptionSpecApplyConfiguration represents an declarative configuration of the PCIDeviceDescriptionSpec type for use
// with apply.
type PCIDeviceDescriptionSpecApplyConfiguration struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// PCIDeviceDescriptionSpecApplyConfiguration constructs an declarative configuration of the PCIDeviceDescriptionSpec type for use with
// apply.
func PCIDeviceDescriptionSpec() *PCIDeviceDescriptionSpecApplyConfiguration {
	return &PCIDeviceDescriptionSpecApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *PCIDeviceDescriptionSpecApplyConfiguration) WithID(value string) *PCIDeviceDescriptionSpecApplyConfiguration {
	b.ID = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PCIDeviceDescriptionSpecApplyConfiguration) WithName(value string) *PCIDeviceDescriptionSpecApplyConfiguration {
	b.Name = &value
	return b
}
