// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha4

// SubnetSpecApplyConfiguration represents an declarative configuration of the SubnetSpec type for use
// with apply.
type SubnetSpecApplyConfiguration struct {
	Subnet        *ObjectReferenceApplyConfiguration `json:"subnet,omitempty"`
	Network       *ObjectReferenceApplyConfiguration `json:"network,omitempty"`
	CIDR          *string                            `json:"cidr,omitempty"`
	Region        *RegionSpecApplyConfiguration      `json:"region,omitempty"`
	AddressFamily *string                            `json:"addressFamily,omitempty"`
}

// SubnetSpecApplyConfiguration constructs an declarative configuration of the SubnetSpec type for use with
// apply.
func SubnetSpec() *SubnetSpecApplyConfiguration {
	return &SubnetSpecApplyConfiguration{}
}

// WithSubnet sets the Subnet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Subnet field is set to the value of the last call.
func (b *SubnetSpecApplyConfiguration) WithSubnet(value *ObjectReferenceApplyConfiguration) *SubnetSpecApplyConfiguration {
	b.Subnet = value
	return b
}

// WithNetwork sets the Network field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Network field is set to the value of the last call.
func (b *SubnetSpecApplyConfiguration) WithNetwork(value *ObjectReferenceApplyConfiguration) *SubnetSpecApplyConfiguration {
	b.Network = value
	return b
}

// WithCIDR sets the CIDR field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CIDR field is set to the value of the last call.
func (b *SubnetSpecApplyConfiguration) WithCIDR(value string) *SubnetSpecApplyConfiguration {
	b.CIDR = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *SubnetSpecApplyConfiguration) WithRegion(value *RegionSpecApplyConfiguration) *SubnetSpecApplyConfiguration {
	b.Region = value
	return b
}

// WithAddressFamily sets the AddressFamily field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AddressFamily field is set to the value of the last call.
func (b *SubnetSpecApplyConfiguration) WithAddressFamily(value string) *SubnetSpecApplyConfiguration {
	b.AddressFamily = &value
	return b
}
