// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha4

// VirtSpecApplyConfiguration represents an declarative configuration of the VirtSpec type for use
// with apply.
type VirtSpecApplyConfiguration struct {
	VMType *string `json:"vmType,omitempty"`
}

// VirtSpecApplyConfiguration constructs an declarative configuration of the VirtSpec type for use with
// apply.
func VirtSpec() *VirtSpecApplyConfiguration {
	return &VirtSpecApplyConfiguration{}
}

// WithVMType sets the VMType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VMType field is set to the value of the last call.
func (b *VirtSpecApplyConfiguration) WithVMType(value string) *VirtSpecApplyConfiguration {
	b.VMType = &value
	return b
}
