apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Chart.Name }}-manager-role"
rules:
  - apiGroups:
      - machine.onmetal.de
    resources:
      - inventories
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - machine.onmetal.de
    resources:
      - inventories/status
    verbs:
      - get
  - apiGroups:
      - machine.onmetal.de
    resources:
      - machines
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - machine.onmetal.de
    resources:
      - machines/status
    verbs:
      - get
  - apiGroups:
      - {{ .Values.crd.switch.group }}
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - {{ .Values.crd.switch.group }}
    resources:
      - {{ .Values.crd.switch.plural }}
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - {{ .Values.crd.switch.group }}
    resources:
      - {{ .Values.crd.switch.plural }}/finalizers
    verbs:
      - update
  - apiGroups:
      - {{ .Values.crd.switch.group }}
    resources:
      - {{ .Values.crd.switch.plural }}/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - {{ .Values.crd.switchAssignment.group }}
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - {{ .Values.crd.switchAssignment.group }}
    resources:
      - {{ .Values.crd.switchAssignment.plural }}
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - {{ .Values.crd.switchAssignment.group }}
    resources:
      - {{ .Values.crd.switchAssignment.plural }}/finalizers
    verbs:
      - update
  - apiGroups:
      - {{ .Values.crd.switchAssignment.group }}
    resources:
      - {{ .Values.crd.switchAssignment.plural }}/status
    verbs:
      - get
      - patch
      - update