# permissions for end users to edit switches.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Chart.Name }}-editor-role"
rules:
- apiGroups:
  - {{ .Values.crd.group }}
  resources:
  - {{ .Values.crd.plural }}
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - {{ .Values.crd.group }}
  resources:
  - {{ .Values.crd.plural }}/status
  verbs:
  - get
