apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Values.namespace }}/{{ .Chart.Name }}{{ .Values.webhooks.cert.nameSuffix}}
  name: {{ .Chart.Name }}-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ .Chart.Name }}{{ .Values.webhooks.service.nameSuffix }}
        namespace: {{ .Values.namespace }}
        path: /mutate-switch-onmetal-de-v1alpha1-switchassignment
    failurePolicy: Fail
    name: mswitchassignment.kb.io
    rules:
      - apiGroups:
          - {{ .Values.crd.switchAssignment.group }}
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - {{ .Values.crd.switchAssignment.plural }}
    sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Values.namespace }}/{{ .Chart.Name }}{{ .Values.webhooks.cert.nameSuffix}}
  name: {{ .Chart.Name }}-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: {{ .Chart.Name }}{{ .Values.webhooks.service.nameSuffix }}
        namespace: {{ .Values.namespace }}
        path: /validate-switch-onmetal-de-v1alpha1-switchassignment
    failurePolicy: Fail
    name: vswitchassignment.kb.io
    rules:
      - apiGroups:
          - {{ .Values.crd.switchAssignment.group }}
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - {{ .Values.crd.switchAssignment.plural }}
    sideEffects: None
