# permissions for end users to view aggregates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregate-viewer-role
rules:
- apiGroups:
  - machine.onmetal.de
  resources:
  - aggregates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - machine.onmetal.de
  resources:
  - aggregates/status
  verbs:
  - get
