
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - machine.onmetal.de
  resources:
  - inventories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - machine.onmetal.de
  resources:
  - inventories/status
  verbs:
  - get
- apiGroups:
  - machine.onmetal.de
  resources:
  - machines
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine.onmetal.de
  resources:
  - machines/status
  verbs:
  - get
- apiGroups:
  - switch.onmetal.de
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - switch.onmetal.de
  resources:
  - switchassignments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - switch.onmetal.de
  resources:
  - switches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - switch.onmetal.de
  resources:
  - switches/finalizers
  verbs:
  - update
- apiGroups:
  - switch.onmetal.de
  resources:
  - switches/status
  verbs:
  - get
  - patch
  - update
