---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - compute.ironcore.dev
  resources:
  - machineclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.ironcore.dev
  resources:
  - machineclasses/finalizers
  verbs:
  - update
- apiGroups:
  - compute.ironcore.dev
  resources:
  - machineclasses/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - compute.ironcore.dev
  resources:
  - machinepools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.ironcore.dev
  resources:
  - machinepools/finalizers
  verbs:
  - update
- apiGroups:
  - compute.ironcore.dev
  resources:
  - machinepools/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - compute.ironcore.dev
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.ironcore.dev
  resources:
  - machines/finalizers
  verbs:
  - update
- apiGroups:
  - compute.ironcore.dev
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ipam.metal.ironcore.dev
  resources:
  - ips
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.metal.ironcore.dev
  resources:
  - ips/status
  verbs:
  - get
- apiGroups:
  - ipam.metal.ironcore.dev
  resources:
  - subnets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.metal.ironcore.dev
  resources:
  - subnets/status
  verbs:
  - get
- apiGroups:
  - ironcore.dev
  resources:
  - oobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ironcore.dev
  resources:
  - oobs/finalizers
  verbs:
  - update
- apiGroups:
  - ironcore.dev
  resources:
  - oobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - aggregates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - aggregates/finalizers
  verbs:
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - aggregates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - benchmarks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - benchmarks/finalizers
  verbs:
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - benchmarks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - inventories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - inventories/finalizers
  verbs:
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - inventories/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - machines/finalizers
  verbs:
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - metalv1alpha4
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - metalv1alpha4/finalizers
  verbs:
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - metalv1alpha4/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - networkswitches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - networkswitches/finalizers
  verbs:
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - networkswitches/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - sizes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - sizes/finalizers
  verbs:
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - sizes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - metal.ironcore.dev
  resources:
  - switchconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
