---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - benchmark.onmetal.de
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - benchmark.onmetal.de
  resources:
  - machines/finalizers
  verbs:
  - update
- apiGroups:
  - benchmark.onmetal.de
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ipam.onmetal.de
  resources:
  - ips
  verbs:
  - create
  - get
  - list
  - patch
  - update
- apiGroups:
  - ipam.onmetal.de
  resources:
  - ips/status
  verbs:
  - get
- apiGroups:
  - ipam.onmetal.de
  resources:
  - subnets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.onmetal.de
  resources:
  - subnets/status
  verbs:
  - get
- apiGroups:
  - machine.onmetal.de
  resources:
  - aggregates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine.onmetal.de
  resources:
  - aggregates/finalizers
  verbs:
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - aggregates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - inventories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine.onmetal.de
  resources:
  - inventories/finalizers
  verbs:
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - inventories/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine.onmetal.de
  resources:
  - machineassignments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine.onmetal.de
  resources:
  - machineassignments/finalizers
  verbs:
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - machineassignments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine.onmetal.de
  resources:
  - machines/finalizers
  verbs:
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - sizes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine.onmetal.de
  resources:
  - sizes/finalizers
  verbs:
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - sizes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - onmetal.de
  resources:
  - oobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - onmetal.de
  resources:
  - oobs/finalizers
  verbs:
  - update
- apiGroups:
  - onmetal.de
  resources:
  - oobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - switch.onmetal.de
  resources:
  - switchconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - switch.onmetal.de
  resources:
  - switches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - switch.onmetal.de
  resources:
  - switches/finalizers
  verbs:
  - update
- apiGroups:
  - switch.onmetal.de
  resources:
  - switches/status
  verbs:
  - get
  - patch
  - update
