
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
<<<<<<< HEAD
  name: metal-api-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - benchmark.onmetal.de
  resources:
  - machines
=======
  name: manager-role
rules:
- apiGroups:
  - machine.onmetal.de
  resources:
  - aggregates
>>>>>>> master-holder
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
<<<<<<< HEAD
  - benchmark.onmetal.de
  resources:
  - machines/finalizers
  verbs:
  - update
- apiGroups:
  - benchmark.onmetal.de
  resources:
  - machines/status
=======
  - machine.onmetal.de
  resources:
  - aggregates/finalizers
  verbs:
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - aggregates/status
>>>>>>> master-holder
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - inventories
  verbs:
<<<<<<< HEAD
=======
  - create
  - delete
>>>>>>> master-holder
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine.onmetal.de
  resources:
  - inventories/finalizers
  verbs:
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - inventories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
<<<<<<< HEAD
  - machines
=======
  - sizes
>>>>>>> master-holder
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine.onmetal.de
  resources:
<<<<<<< HEAD
  - machines/finalizers
=======
  - sizes/finalizers
>>>>>>> master-holder
  verbs:
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
<<<<<<< HEAD
  - machines/status
=======
  - sizes/status
>>>>>>> master-holder
  verbs:
  - get
  - patch
  - update
<<<<<<< HEAD
- apiGroups:
  - oob.onmetal.de
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oob.onmetal.de
  resources:
  - machines/finalizers
  verbs:
  - update
- apiGroups:
  - oob.onmetal.de
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - switch.onmetal.de
  resources:
  - switches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
=======
>>>>>>> master-holder
