---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - benchmark.onmetal.de
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - benchmark.onmetal.de
  resources:
  - machines/finalizers
  verbs:
  - update
- apiGroups:
  - benchmark.onmetal.de
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ipam.onmetal.de
  resources:
  - ips
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - watch
- apiGroups:
  - ipam.onmetal.de
  resources:
  - ips/status
  verbs:
  - get
  - update
- apiGroups:
  - ipam.onmetal.de
  resources:
  - subnets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - watch
- apiGroups:
  - ipam.onmetal.de
  resources:
  - subnets/status
  verbs:
  - get
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - aggregates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine.onmetal.de
  resources:
  - aggregates/finalizers
  verbs:
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - aggregates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - inventories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine.onmetal.de
  resources:
  - inventories/finalizers
  verbs:
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - inventories/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine.onmetal.de
  resources:
  - machines/finalizers
  verbs:
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - requests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine.onmetal.de
  resources:
  - requests/finalizers
  verbs:
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - requests/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - sizes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine.onmetal.de
  resources:
  - sizes/finalizers
  verbs:
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - sizes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - oob.onmetal.de
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oob.onmetal.de
  resources:
  - machines/finalizers
  verbs:
  - update
- apiGroups:
  - oob.onmetal.de
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - switch.onmetal.de
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - switch.onmetal.de
  resources:
  - switchassignments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - switch.onmetal.de
  resources:
  - switchassignments/finalizers
  verbs:
  - update
- apiGroups:
  - switch.onmetal.de
  resources:
  - switchassignments/status
  verbs:
  - update
- apiGroups:
  - switch.onmetal.de
  resources:
  - switches
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - switch.onmetal.de
  resources:
  - switches/finalizers
  verbs:
  - update
- apiGroups:
  - switch.onmetal.de
  resources:
  - switches/status
  verbs:
  - get
  - patch
  - update
