# permissions for end users to view switchconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: switchconfig-viewer-role
rules:
- apiGroups:
  - metal.ironcore.dev
  resources:
  - switchconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - switchconfigs/status
  verbs:
  - get
