# permissions for end users to edit switchconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: switchconfig-editor-role
rules:
- apiGroups:
  - metal.ironcore.dev
  resources:
  - switchconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal.ironcore.dev
  resources:
  - switchconfigs/status
  verbs:
  - get
