# permissions for end users to view switchassignments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: switchassignment-viewer-role
rules:
- apiGroups:
  - switch.onmetal.de
  resources:
  - switchassignments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - switch.onmetal.de
  resources:
  - switchassignments/status
  verbs:
  - get
