# permissions for end users to edit switchassignments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: switchassignment-editor-role
rules:
- apiGroups:
  - switch.onmetal.de
  resources:
  - switchassignments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - switch.onmetal.de
  resources:
  - switchassignments/status
  verbs:
  - get
