/*
Copyright (c) 2023 T-Systems International GmbH, SAP SE or an SAP affiliate company. All right reserved

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/onmetal/metal-api/apis/inventory/v1alpha1"
)

// LLDPSpecApplyConfiguration represents an declarative configuration of the LLDPSpec type for use
// with apply.
type LLDPSpecApplyConfiguration struct {
	ChassisID         *string                     `json:"chassisId,omitempty"`
	SystemName        *string                     `json:"systemName,omitempty"`
	SystemDescription *string                     `json:"systemDescription,omitempty"`
	PortID            *string                     `json:"portId,omitempty"`
	PortDescription   *string                     `json:"portDescription,omitempty"`
	Capabilities      []v1alpha1.LLDPCapabilities `json:"capabilities,omitempty"`
}

// LLDPSpecApplyConfiguration constructs an declarative configuration of the LLDPSpec type for use with
// apply.
func LLDPSpec() *LLDPSpecApplyConfiguration {
	return &LLDPSpecApplyConfiguration{}
}

// WithChassisID sets the ChassisID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ChassisID field is set to the value of the last call.
func (b *LLDPSpecApplyConfiguration) WithChassisID(value string) *LLDPSpecApplyConfiguration {
	b.ChassisID = &value
	return b
}

// WithSystemName sets the SystemName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SystemName field is set to the value of the last call.
func (b *LLDPSpecApplyConfiguration) WithSystemName(value string) *LLDPSpecApplyConfiguration {
	b.SystemName = &value
	return b
}

// WithSystemDescription sets the SystemDescription field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SystemDescription field is set to the value of the last call.
func (b *LLDPSpecApplyConfiguration) WithSystemDescription(value string) *LLDPSpecApplyConfiguration {
	b.SystemDescription = &value
	return b
}

// WithPortID sets the PortID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortID field is set to the value of the last call.
func (b *LLDPSpecApplyConfiguration) WithPortID(value string) *LLDPSpecApplyConfiguration {
	b.PortID = &value
	return b
}

// WithPortDescription sets the PortDescription field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortDescription field is set to the value of the last call.
func (b *LLDPSpecApplyConfiguration) WithPortDescription(value string) *LLDPSpecApplyConfiguration {
	b.PortDescription = &value
	return b
}

// WithCapabilities adds the given value to the Capabilities field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Capabilities field.
func (b *LLDPSpecApplyConfiguration) WithCapabilities(values ...v1alpha1.LLDPCapabilities) *LLDPSpecApplyConfiguration {
	for i := range values {
		b.Capabilities = append(b.Capabilities, values[i])
	}
	return b
}
