apiVersion: ipam.ironcore.dev/v1alpha1
kind: Subnet
metadata:
  name: switch-ranges-v4
  namespace: ironcore
  labels:
    ipam.ironcore.dev/object-purpose: "switch-carrier"
spec:
  cidr: "100.64.0.0/16"
  network:
    name: underlay
  regions:
    - availabilityZones:
        - B
      name: eu-central