apiVersion: switch.onmetal.de/v1beta1
kind: SwitchConfig
metadata:
  name: spines-config
  namespace: onmetal
  labels:
    switch.onmetal.de/type-spine: "true"
spec:
  switches:
    matchLabels:
      switch.onmetal.de/type: "spine"
  portsDefaults:
    lanes: 4
    mtu: 9100
    ipv4MaskLength: 30
    ipv6Prefix: 112
    state: "up"
    fec: "rs"
  ipam:
    addressFamily:
      ipv4: true
      ipv6: true
    carrierSubnets:
      labelSelector:
        matchLabels:
          ipam.onmetal.de/object-purpose: "switch-carrier"
    loopbackSubnets:
      labelSelector:
        matchLabels:
          ipam.onmetal.de/object-purpose: "switch-loopbacks"
    southSubnets:
      labelSelector:
        matchLabels:
          ipam.onmetal.de/object-purpose: "south-subnet"
      fieldSelector:
        labelKey: "ipam.onmetal.de/object-owner"
        fieldRef:
          fieldPath: "metadata.name"
    loopbackAddresses:
      labelSelector:
        matchLabels:
          ipam.onmetal.de/object-purpose: "loopback"
      fieldSelector:
        labelKey: "ipam.onmetal.de/object-owner"
        fieldRef:
          fieldPath: "metadata.name"