resources:
  - leaf-1.fra3.infra.onmetal.de.yaml
  - leaf-2.fra3.infra.onmetal.de.yaml
  - leaf-3.fra3.infra.onmetal.de.yaml
  - leaf-4.fra3.infra.onmetal.de.yaml
  - leaf-5.fra3.infra.onmetal.de.yaml
  - leaf-6.fra3.infra.onmetal.de.yaml
  - leaf-7.fra3.infra.onmetal.de.yaml
  - spine-0-1.fra3.infra.onmetal.de.yaml
  - spine-0-2.fra3.infra.onmetal.de.yaml
  - spine-0-3.fra3.infra.onmetal.de.yaml
  - spine-1-1.fra3.infra.onmetal.de.yaml
  - spine-1-2.fra3.infra.onmetal.de.yaml
  - spine-1-3.fra3.infra.onmetal.de.yaml
  - spine-1-4.fra3.infra.onmetal.de.yaml
  - spine-1-5.fra3.infra.onmetal.de.yaml
  - spine-1-6.fra3.infra.onmetal.de.yaml