apiVersion: switch.onmetal.de/v1alpha1
kind: Switch
metadata:
  name: 1403e326-47e9-32f4-b48c-bdd8869e9717
  namespace: onmetal
spec:
  chassis:
    chassisId: 68:21:5f:47:17:6e
    manufacturer: Accton
    serial: 772632X1950887
    sku: "1"
  distro:
    asic: broadcom
    os: SONiC
    version: 7145582a
  hostname: leaf-7.fra3.infra.onmetal.de
  interfaces:
    Ethernet0:
      ipv4: 100.79.246.50/30
      ipv6: 2001:db8:1000:12:ffff:f800:0:19/127
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
      peerChassisId: 68:21:5f:47:0b:18
      peerPortDescription: Ethernet12
      peerPortId: Eth35/1
      peerSystemName: spine-1-5.fra3.infra.onmetal.de
      peerType: Switch
    Ethernet4:
      ipv4: 100.79.252.50/30
      ipv6: 2001:db8:1000:12:ffff:8000:0:19/127
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
      peerChassisId: 68:21:5f:47:0a:6f
      peerPortDescription: Ethernet12
      peerPortId: Eth35/1
      peerSystemName: spine-1-6.fra3.infra.onmetal.de
      peerType: Switch
    Ethernet8:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet12:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet16:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet20:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet24:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet28:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet32:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet36:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet40:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet44:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet48:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet52:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet56:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet60:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet64:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet68:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet72:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet76:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet80:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet84:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet88:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet92:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet96:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet100:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet104:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet108:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet112:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet116:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet120:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    Ethernet124:
      lanes: 4
      macAddress: 68:21:5f:47:17:6e
      speed: 100000
    eth0:
      lanes: 1
      macAddress: 68:21:5f:47:17:6e
      speed: 1000
      peerChassisId: 64:9d:99:15:56:1c
      peerPortDescription: Ethernet Port on unit 1, port 44
      peerPortId: Eth 1/44
      peerSystemName: mgmt-sw-1
      peerType: Switch
  location: {}
  switchPorts: 32
  totalPorts: 35
status:
  connectionLevel: 2
  northConnections:
    count: 2
    peers:
      Ethernet0:
        chassisId: 68:21:5f:47:0b:18
        name: 1b96a853-1fd5-3b8c-a6c7-cc2fb47a2621
        namespace: onmetal
        portName: Ethernet12
        type: Switch
      Ethernet4:
        chassisId: 68:21:5f:47:0a:6f
        name: 7dc0d671-79cb-3394-b1de-e9eeb6dd6340
        namespace: onmetal
        portName: Ethernet12
        type: Switch
  role: Spine
  scanPorts: false
  southConnections:
    count: 0
    peers: {}
  southSubnetV4:
    cidr: 100.79.230.0/23
    parentSubnet:
      name: subnet-sample-v4
      namespace: onmetal
  southSubnetV6:
    cidr: 2001:db8:1000:12:ffff:fff8::/120
    parentSubnet:
      name: subnet-sample-v6
      namespace: onmetal
  state: Finished
