apiVersion: v1
kind: Service
metadata:
  name: manager-service
  namespace: system
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: metal-api-server-exploitation