apiVersion: switch.onmetal.de/v1alpha1
kind: SwitchAssignment
metadata:
  name: switchassignment-1950115
spec:
  serial: "1950115"
  chassisId: 68:21:5f:47:0d:6e
  region: "EU-West"
  availabilityZone: "A"