apiVersion: machine.onmetal.de/v1alpha1
kind: Inventory
metadata:
  name: a967954c-3475-11b2-a85c-84d8b4f8cd2d
spec:
  system:
    id: a967954c-3475-11b2-a85c-84d8b4f8cd2d
    manufacturer: LENOVO
    productSku: LENOVO_MT_20JX_BU_Think_FM_ThinkPad T570 W10DG
    serialNumber: R90QR6J0
  ipmis:
    - ipAddress: 192.168.10.191
      macAddress: 38:68:dd:26:8d:f5
  blocks:
    count: 1
    capacity: 256060514304
    blocks:
      - name: nvme0n1
        type: NVMe
        rotational: false
        bus:
        model: SAMSUNG MZVLW256HEHP-000L7"
        size: 256060514304
        partitionTable:
          type: GPT
          partitions:
            - id: 0624092B-A594-44A7-BEE7-A6D6582D399A
              name: EFI System Partition
              size: 104857600
  memory:
    total: 16620400640
  cpus:
    sockets: 1
    cores: 2
    threads: 4
    cpus:
      - physicalId: 0
        logicalIds: [0, 1, 2, 3]
        cores: 2
        siblings: 4
        vendorId: GenuineIntel
        family: "6"
        model: "78"
        modelName: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
        stepping: "3"
        microcode: "0xe2"
        mhz: "2799.699"
        cacheSize: 3072 KB
        fpu: true
        fpuException: true
        cpuIdLevel: 22
        wp: true
        flags: ["fpu", "vme", "de", "pse", "tsc", "msr", "pae", "mce"]
        vmxFlags: ["vnmi", "preemption_timer", "invvpid", "ept_x_only", "ept_ad", "ept_1gb"]
        bugs: ["cpu_meltdown", "spectre_v1", "spectre_v2"]
        bogoMips: "4999.9"
        clFlushSize: 64
        cacheAlignment: 64
        addressSizes: "39 bits physical, 48 bits virtual"
        powerManagement:
  nics:
    count : 1
    nics:
      - name: enp0s31f6
        pciAddress: 0000:00:1f.6
        macAddress: 48:2a:e3:02:d9:e8
        mtu: 1500
        speed: 1000
        lldps:
          - chassisId: 3c:2c:99:9d:cd:48
            systemName: EC1817001226
            systemDescription: ECS4100-52T
            portId: 3c:2c:99:9d:cd:77
            portDescription: Ethernet Port on unit 1, port 47
        ndps:
          - ipAddress: ff02::1:3
            macAddress: 33:33:00:01:00:03
            state: Reachable
  virt:
    vmType: none