apiVersion: switch.onmetal.de/v1alpha1
kind: Switch
metadata:
  name: 92b9de0f-19f2-3f3b-95d0-fb668b1d3d3b
  namespace: onmetal
spec:
  hostname: spine-0-1.fra3.infra.onmetal.de
  interfaces:
    Ethernet0:
      lanes: 4
      lldpChassisId: 68:21:5f:47:0d:5a
      lldpPortDescription: Ethernet0
      lldpPortId: Eth29/1
      lldpSystemName: spine-1-1.fra3.infra.onmetal.de
      macAddress: 68:21:5f:47:0d:6e
      neighbour: Switch
    Ethernet12:
      lanes: 4
      lldpChassisId: 68:21:5f:47:0b:18
      lldpPortDescription: Ethernet0
      lldpPortId: Eth29/1
      lldpSystemName: spine-1-5.fra3.infra.onmetal.de
      macAddress: 68:21:5f:47:0d:6e
      neighbour: Switch
    Ethernet4:
      lanes: 4
      lldpChassisId: 68:21:5f:47:0b:5b
      lldpPortDescription: Ethernet0
      lldpPortId: Eth29/1
      lldpSystemName: spine-1-2.fra3.infra.onmetal.de
      macAddress: 68:21:5f:47:0d:6e
      neighbour: Switch
    Ethernet8:
      lanes: 4
      lldpChassisId: 68:21:5f:47:0a:5a
      lldpPortDescription: Ethernet0
      lldpPortId: Eth29/1
      lldpSystemName: spine-1-3.fra3.infra.onmetal.de
      macAddress: 68:21:5f:47:0d:6e
      neighbour: Switch
    eth0:
      lanes: 1
      lldpChassisId: 64:9d:99:15:56:1c
      lldpPortDescription: Ethernet Port on unit 1, port 44
      lldpPortId: Eth 1/44
      lldpSystemName: mgmt-sw-1
      macAddress: 68:21:5f:47:0d:6e
      neighbour: Switch
  ports: 5
  scanPorts: true
  state:
    connectionLevel: 255
    northConnections:
      connections: []
      count: 0
    role: Spine
    southConnections:
      connections:
      - chassisId: 68:21:5f:47:0d:5a
        name: ""
        namespace: ""
        type: Switch
      - chassisId: 68:21:5f:47:0b:18
        name: ""
        namespace: ""
        type: Switch
      - chassisId: 68:21:5f:47:0b:5b
        name: ""
        namespace: ""
        type: Switch
      - chassisId: 68:21:5f:47:0a:5a
        name: ""
        namespace: ""
        type: Switch
      count: 4
  switchChassis:
    chassisId: 68:21:5f:47:0d:6e
    manufacturer: Accton
    serial: 772632X1950115
    sku: "1"
  switchDistro:
    asic: broadcom
    os: SONiC
    version: 7145582a
  switchPorts: 4
