apiVersion: metal.ironcore.dev/v1beta1
kind: SwitchConfig
metadata:
  name: switchconfig-sample
spec:
  switches:
    matchLabels:
      metal.ironcore.dev/type: "spine"
  portsDefaults:
    fec: "rs"
    ipv4MaskLength: 30
    ipv6Prefix: 112
    mtu: 9100
    state: "up"
  ipam:
    addressFamily:
      ipv4: true
      ipv6: true
    carrierSubnets:
      labelSelector:
        matchLabels:
          ipam.ironcore.dev/object-purpose: "switch-carrier"
    loopbackSubnets:
      labelSelector:
        matchLabels:
          ipam.ironcore.dev/object-purpose: "switch-loopbacks"
    southSubnets:
      labelSelector:
        matchLabels:
          ipam.ironcore.dev/object-purpose: "south-subnet"
      fieldSelector:
        labelKey: "ipam.ironcore.dev/object-owner"
        fieldRef:
          fieldPath: "metadata.name"
    loopbackAddresses:
      labelSelector:
        matchLabels:
          ipam.ironcore.dev/object-purpose: "loopback"
      fieldSelector:
        labelKey: "ipam.ironcore.dev/object-owner"
        fieldRef:
          fieldPath: "metadata.name"