// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha4

type AggregateExpansion interface{}

type BenchmarkExpansion interface{}

type InventoryExpansion interface{}

type MachineExpansion interface{}

type NetworkSwitchExpansion interface{}

type SizeExpansion interface{}

type SwitchConfigExpansion interface{}
