// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package v1alpha4

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha4 "github.com/ironcore-dev/metal/apis/metal/v1alpha4"
	metalv1alpha4 "github.com/ironcore-dev/metal/client/applyconfiguration/metal/v1alpha4"
	scheme "github.com/ironcore-dev/metal/client/metal/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NetworkSwitchesGetter has a method to return a NetworkSwitchInterface.
// A group's client should implement this interface.
type NetworkSwitchesGetter interface {
	NetworkSwitches(namespace string) NetworkSwitchInterface
}

// NetworkSwitchInterface has methods to work with NetworkSwitch resources.
type NetworkSwitchInterface interface {
	Create(ctx context.Context, networkSwitch *v1alpha4.NetworkSwitch, opts v1.CreateOptions) (*v1alpha4.NetworkSwitch, error)
	Update(ctx context.Context, networkSwitch *v1alpha4.NetworkSwitch, opts v1.UpdateOptions) (*v1alpha4.NetworkSwitch, error)
	UpdateStatus(ctx context.Context, networkSwitch *v1alpha4.NetworkSwitch, opts v1.UpdateOptions) (*v1alpha4.NetworkSwitch, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha4.NetworkSwitch, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha4.NetworkSwitchList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha4.NetworkSwitch, err error)
	Apply(ctx context.Context, networkSwitch *metalv1alpha4.NetworkSwitchApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha4.NetworkSwitch, err error)
	ApplyStatus(ctx context.Context, networkSwitch *metalv1alpha4.NetworkSwitchApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha4.NetworkSwitch, err error)
	NetworkSwitchExpansion
}

// networkSwitches implements NetworkSwitchInterface
type networkSwitches struct {
	client rest.Interface
	ns     string
}

// newNetworkSwitches returns a NetworkSwitches
func newNetworkSwitches(c *MetalV1alpha4Client, namespace string) *networkSwitches {
	return &networkSwitches{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the networkSwitch, and returns the corresponding networkSwitch object, and an error if there is any.
func (c *networkSwitches) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha4.NetworkSwitch, err error) {
	result = &v1alpha4.NetworkSwitch{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("networkswitches").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of NetworkSwitches that match those selectors.
func (c *networkSwitches) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha4.NetworkSwitchList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha4.NetworkSwitchList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("networkswitches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested networkSwitches.
func (c *networkSwitches) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("networkswitches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a networkSwitch and creates it.  Returns the server's representation of the networkSwitch, and an error, if there is any.
func (c *networkSwitches) Create(ctx context.Context, networkSwitch *v1alpha4.NetworkSwitch, opts v1.CreateOptions) (result *v1alpha4.NetworkSwitch, err error) {
	result = &v1alpha4.NetworkSwitch{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("networkswitches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(networkSwitch).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a networkSwitch and updates it. Returns the server's representation of the networkSwitch, and an error, if there is any.
func (c *networkSwitches) Update(ctx context.Context, networkSwitch *v1alpha4.NetworkSwitch, opts v1.UpdateOptions) (result *v1alpha4.NetworkSwitch, err error) {
	result = &v1alpha4.NetworkSwitch{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("networkswitches").
		Name(networkSwitch.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(networkSwitch).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *networkSwitches) UpdateStatus(ctx context.Context, networkSwitch *v1alpha4.NetworkSwitch, opts v1.UpdateOptions) (result *v1alpha4.NetworkSwitch, err error) {
	result = &v1alpha4.NetworkSwitch{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("networkswitches").
		Name(networkSwitch.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(networkSwitch).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the networkSwitch and deletes it. Returns an error if one occurs.
func (c *networkSwitches) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("networkswitches").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *networkSwitches) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("networkswitches").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched networkSwitch.
func (c *networkSwitches) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha4.NetworkSwitch, err error) {
	result = &v1alpha4.NetworkSwitch{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("networkswitches").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied networkSwitch.
func (c *networkSwitches) Apply(ctx context.Context, networkSwitch *metalv1alpha4.NetworkSwitchApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha4.NetworkSwitch, err error) {
	if networkSwitch == nil {
		return nil, fmt.Errorf("networkSwitch provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(networkSwitch)
	if err != nil {
		return nil, err
	}
	name := networkSwitch.Name
	if name == nil {
		return nil, fmt.Errorf("networkSwitch.Name must be provided to Apply")
	}
	result = &v1alpha4.NetworkSwitch{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("networkswitches").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *networkSwitches) ApplyStatus(ctx context.Context, networkSwitch *metalv1alpha4.NetworkSwitchApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha4.NetworkSwitch, err error) {
	if networkSwitch == nil {
		return nil, fmt.Errorf("networkSwitch provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(networkSwitch)
	if err != nil {
		return nil, err
	}

	name := networkSwitch.Name
	if name == nil {
		return nil, fmt.Errorf("networkSwitch.Name must be provided to Apply")
	}

	result = &v1alpha4.NetworkSwitch{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("networkswitches").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
