apiVersion: ipam.onmetal.de/v1alpha1
kind: IP
metadata:
  name: leaf-2-loopback-v4
  namespace: onmetal
  labels:
    ipam.onmetal.de/object-purpose: "loopback"
    ipam.onmetal.de/object-owner: "044ca7d1-c6f8-37d8-83ce-bf6a18318f2d"
spec:
  subnet:
    name: loopbacks-v4
  ip: 100.64.255.4
status:
  reserved: "100.64.255.4"
  state: "Finished"