---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - machine.onmetal.de
  resources:
  - machineassignments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine.onmetal.de
  resources:
  - machineassignments/finalizers
  verbs:
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - machineassignments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - machines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine.onmetal.de
  resources:
  - machines/finalizers
  verbs:
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - oob.onmetal.de
  resources:
  - machines
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oob.onmetal.de
  resources:
  - machines/finalizers
  verbs:
  - update
- apiGroups:
  - oob.onmetal.de
  resources:
  - machines/status
  verbs:
  - get
  - patch
  - update
