apiVersion: switch.onmetal.de/v1beta1
kind: Switch
metadata:
  name: b9a234a5-416b-3d49-a4f8-65b6f30c8ee5
  namespace: onmetal
  labels:
    switch.onmetal.de/inventoried: "true"
  annotations:
    hardware/chassis-id: 68215f47166e
spec:
  inventoryRef:
    name: "b9a234a5-416b-3d49-a4f8-65b6f30c8ee5"
  topSpine: false
  managed: true
  cordon: false
  scanPorts: true