apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  namespace: system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: metal-api-scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metal-api-scheduler
    spec:
      serviceAccountName: manager
      terminationGracePeriodSeconds: 10
      securityContext: {}
      containers:
        - name: deployment
          securityContext:
            runAsGroup: 65532
            runAsNonRoot: true
            runAsUser: 65532
            allowPrivilegeEscalation: false
          image: deployment:latest
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          imagePullPolicy: IfNotPresent
          ports:
            - name: https
              containerPort: 9443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 1024Mi              