// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha4 "github.com/ironcore-dev/metal/apis/metal/v1alpha4"
	metalv1alpha4 "github.com/ironcore-dev/metal/client/applyconfiguration/metal/v1alpha4"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNetworkSwitches implements NetworkSwitchInterface
type FakeNetworkSwitches struct {
	Fake *FakeMetalV1alpha4
	ns   string
}

var networkswitchesResource = v1alpha4.SchemeGroupVersion.WithResource("networkswitches")

var networkswitchesKind = v1alpha4.SchemeGroupVersion.WithKind("NetworkSwitch")

// Get takes name of the networkSwitch, and returns the corresponding networkSwitch object, and an error if there is any.
func (c *FakeNetworkSwitches) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha4.NetworkSwitch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(networkswitchesResource, c.ns, name), &v1alpha4.NetworkSwitch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.NetworkSwitch), err
}

// List takes label and field selectors, and returns the list of NetworkSwitches that match those selectors.
func (c *FakeNetworkSwitches) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha4.NetworkSwitchList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(networkswitchesResource, networkswitchesKind, c.ns, opts), &v1alpha4.NetworkSwitchList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha4.NetworkSwitchList{ListMeta: obj.(*v1alpha4.NetworkSwitchList).ListMeta}
	for _, item := range obj.(*v1alpha4.NetworkSwitchList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested networkSwitches.
func (c *FakeNetworkSwitches) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(networkswitchesResource, c.ns, opts))

}

// Create takes the representation of a networkSwitch and creates it.  Returns the server's representation of the networkSwitch, and an error, if there is any.
func (c *FakeNetworkSwitches) Create(ctx context.Context, networkSwitch *v1alpha4.NetworkSwitch, opts v1.CreateOptions) (result *v1alpha4.NetworkSwitch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(networkswitchesResource, c.ns, networkSwitch), &v1alpha4.NetworkSwitch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.NetworkSwitch), err
}

// Update takes the representation of a networkSwitch and updates it. Returns the server's representation of the networkSwitch, and an error, if there is any.
func (c *FakeNetworkSwitches) Update(ctx context.Context, networkSwitch *v1alpha4.NetworkSwitch, opts v1.UpdateOptions) (result *v1alpha4.NetworkSwitch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(networkswitchesResource, c.ns, networkSwitch), &v1alpha4.NetworkSwitch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.NetworkSwitch), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNetworkSwitches) UpdateStatus(ctx context.Context, networkSwitch *v1alpha4.NetworkSwitch, opts v1.UpdateOptions) (*v1alpha4.NetworkSwitch, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(networkswitchesResource, "status", c.ns, networkSwitch), &v1alpha4.NetworkSwitch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.NetworkSwitch), err
}

// Delete takes name of the networkSwitch and deletes it. Returns an error if one occurs.
func (c *FakeNetworkSwitches) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(networkswitchesResource, c.ns, name, opts), &v1alpha4.NetworkSwitch{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetworkSwitches) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(networkswitchesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha4.NetworkSwitchList{})
	return err
}

// Patch applies the patch and returns the patched networkSwitch.
func (c *FakeNetworkSwitches) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha4.NetworkSwitch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(networkswitchesResource, c.ns, name, pt, data, subresources...), &v1alpha4.NetworkSwitch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.NetworkSwitch), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied networkSwitch.
func (c *FakeNetworkSwitches) Apply(ctx context.Context, networkSwitch *metalv1alpha4.NetworkSwitchApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha4.NetworkSwitch, err error) {
	if networkSwitch == nil {
		return nil, fmt.Errorf("networkSwitch provided to Apply must not be nil")
	}
	data, err := json.Marshal(networkSwitch)
	if err != nil {
		return nil, err
	}
	name := networkSwitch.Name
	if name == nil {
		return nil, fmt.Errorf("networkSwitch.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(networkswitchesResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha4.NetworkSwitch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.NetworkSwitch), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeNetworkSwitches) ApplyStatus(ctx context.Context, networkSwitch *metalv1alpha4.NetworkSwitchApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha4.NetworkSwitch, err error) {
	if networkSwitch == nil {
		return nil, fmt.Errorf("networkSwitch provided to Apply must not be nil")
	}
	data, err := json.Marshal(networkSwitch)
	if err != nil {
		return nil, err
	}
	name := networkSwitch.Name
	if name == nil {
		return nil, fmt.Errorf("networkSwitch.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(networkswitchesResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha4.NetworkSwitch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.NetworkSwitch), err
}
