// SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha4 "github.com/ironcore-dev/metal/apis/metal/v1alpha4"
	metalv1alpha4 "github.com/ironcore-dev/metal/client/applyconfiguration/metal/v1alpha4"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSizes implements SizeInterface
type FakeSizes struct {
	Fake *FakeMetalV1alpha4
	ns   string
}

var sizesResource = v1alpha4.SchemeGroupVersion.WithResource("sizes")

var sizesKind = v1alpha4.SchemeGroupVersion.WithKind("Size")

// Get takes name of the size, and returns the corresponding size object, and an error if there is any.
func (c *FakeSizes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha4.Size, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sizesResource, c.ns, name), &v1alpha4.Size{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.Size), err
}

// List takes label and field selectors, and returns the list of Sizes that match those selectors.
func (c *FakeSizes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha4.SizeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sizesResource, sizesKind, c.ns, opts), &v1alpha4.SizeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha4.SizeList{ListMeta: obj.(*v1alpha4.SizeList).ListMeta}
	for _, item := range obj.(*v1alpha4.SizeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sizes.
func (c *FakeSizes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sizesResource, c.ns, opts))

}

// Create takes the representation of a size and creates it.  Returns the server's representation of the size, and an error, if there is any.
func (c *FakeSizes) Create(ctx context.Context, size *v1alpha4.Size, opts v1.CreateOptions) (result *v1alpha4.Size, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sizesResource, c.ns, size), &v1alpha4.Size{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.Size), err
}

// Update takes the representation of a size and updates it. Returns the server's representation of the size, and an error, if there is any.
func (c *FakeSizes) Update(ctx context.Context, size *v1alpha4.Size, opts v1.UpdateOptions) (result *v1alpha4.Size, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sizesResource, c.ns, size), &v1alpha4.Size{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.Size), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSizes) UpdateStatus(ctx context.Context, size *v1alpha4.Size, opts v1.UpdateOptions) (*v1alpha4.Size, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(sizesResource, "status", c.ns, size), &v1alpha4.Size{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.Size), err
}

// Delete takes name of the size and deletes it. Returns an error if one occurs.
func (c *FakeSizes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(sizesResource, c.ns, name, opts), &v1alpha4.Size{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSizes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sizesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha4.SizeList{})
	return err
}

// Patch applies the patch and returns the patched size.
func (c *FakeSizes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha4.Size, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sizesResource, c.ns, name, pt, data, subresources...), &v1alpha4.Size{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.Size), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied size.
func (c *FakeSizes) Apply(ctx context.Context, size *metalv1alpha4.SizeApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha4.Size, err error) {
	if size == nil {
		return nil, fmt.Errorf("size provided to Apply must not be nil")
	}
	data, err := json.Marshal(size)
	if err != nil {
		return nil, err
	}
	name := size.Name
	if name == nil {
		return nil, fmt.Errorf("size.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sizesResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha4.Size{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.Size), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeSizes) ApplyStatus(ctx context.Context, size *metalv1alpha4.SizeApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha4.Size, err error) {
	if size == nil {
		return nil, fmt.Errorf("size provided to Apply must not be nil")
	}
	data, err := json.Marshal(size)
	if err != nil {
		return nil, err
	}
	name := size.Name
	if name == nil {
		return nil, fmt.Errorf("size.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sizesResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha4.Size{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.Size), err
}
