// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha4 "github.com/ironcore-dev/metal/apis/metal/v1alpha4"
	metalv1alpha4 "github.com/ironcore-dev/metal/client/applyconfiguration/metal/v1alpha4"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAggregates implements AggregateInterface
type FakeAggregates struct {
	Fake *FakeMetalV1alpha4
	ns   string
}

var aggregatesResource = v1alpha4.SchemeGroupVersion.WithResource("aggregates")

var aggregatesKind = v1alpha4.SchemeGroupVersion.WithKind("Aggregate")

// Get takes name of the aggregate, and returns the corresponding aggregate object, and an error if there is any.
func (c *FakeAggregates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha4.Aggregate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(aggregatesResource, c.ns, name), &v1alpha4.Aggregate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.Aggregate), err
}

// List takes label and field selectors, and returns the list of Aggregates that match those selectors.
func (c *FakeAggregates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha4.AggregateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(aggregatesResource, aggregatesKind, c.ns, opts), &v1alpha4.AggregateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha4.AggregateList{ListMeta: obj.(*v1alpha4.AggregateList).ListMeta}
	for _, item := range obj.(*v1alpha4.AggregateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested aggregates.
func (c *FakeAggregates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(aggregatesResource, c.ns, opts))

}

// Create takes the representation of a aggregate and creates it.  Returns the server's representation of the aggregate, and an error, if there is any.
func (c *FakeAggregates) Create(ctx context.Context, aggregate *v1alpha4.Aggregate, opts v1.CreateOptions) (result *v1alpha4.Aggregate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(aggregatesResource, c.ns, aggregate), &v1alpha4.Aggregate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.Aggregate), err
}

// Update takes the representation of a aggregate and updates it. Returns the server's representation of the aggregate, and an error, if there is any.
func (c *FakeAggregates) Update(ctx context.Context, aggregate *v1alpha4.Aggregate, opts v1.UpdateOptions) (result *v1alpha4.Aggregate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(aggregatesResource, c.ns, aggregate), &v1alpha4.Aggregate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.Aggregate), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAggregates) UpdateStatus(ctx context.Context, aggregate *v1alpha4.Aggregate, opts v1.UpdateOptions) (*v1alpha4.Aggregate, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(aggregatesResource, "status", c.ns, aggregate), &v1alpha4.Aggregate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.Aggregate), err
}

// Delete takes name of the aggregate and deletes it. Returns an error if one occurs.
func (c *FakeAggregates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(aggregatesResource, c.ns, name, opts), &v1alpha4.Aggregate{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAggregates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(aggregatesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha4.AggregateList{})
	return err
}

// Patch applies the patch and returns the patched aggregate.
func (c *FakeAggregates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha4.Aggregate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(aggregatesResource, c.ns, name, pt, data, subresources...), &v1alpha4.Aggregate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.Aggregate), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied aggregate.
func (c *FakeAggregates) Apply(ctx context.Context, aggregate *metalv1alpha4.AggregateApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha4.Aggregate, err error) {
	if aggregate == nil {
		return nil, fmt.Errorf("aggregate provided to Apply must not be nil")
	}
	data, err := json.Marshal(aggregate)
	if err != nil {
		return nil, err
	}
	name := aggregate.Name
	if name == nil {
		return nil, fmt.Errorf("aggregate.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(aggregatesResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha4.Aggregate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.Aggregate), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeAggregates) ApplyStatus(ctx context.Context, aggregate *metalv1alpha4.AggregateApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha4.Aggregate, err error) {
	if aggregate == nil {
		return nil, fmt.Errorf("aggregate provided to Apply must not be nil")
	}
	data, err := json.Marshal(aggregate)
	if err != nil {
		return nil, err
	}
	name := aggregate.Name
	if name == nil {
		return nil, fmt.Errorf("aggregate.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(aggregatesResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha4.Aggregate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.Aggregate), err
}
