// SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and IronCore contributors
// SPDX-License-Identifier: Apache-2.0

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha4 "github.com/ironcore-dev/metal/apis/metal/v1alpha4"
	metalv1alpha4 "github.com/ironcore-dev/metal/client/applyconfiguration/metal/v1alpha4"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeInventories implements InventoryInterface
type FakeInventories struct {
	Fake *FakeMetalV1alpha4
	ns   string
}

var inventoriesResource = v1alpha4.SchemeGroupVersion.WithResource("inventories")

var inventoriesKind = v1alpha4.SchemeGroupVersion.WithKind("Inventory")

// Get takes name of the inventory, and returns the corresponding inventory object, and an error if there is any.
func (c *FakeInventories) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha4.Inventory, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(inventoriesResource, c.ns, name), &v1alpha4.Inventory{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.Inventory), err
}

// List takes label and field selectors, and returns the list of Inventories that match those selectors.
func (c *FakeInventories) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha4.InventoryList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(inventoriesResource, inventoriesKind, c.ns, opts), &v1alpha4.InventoryList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha4.InventoryList{ListMeta: obj.(*v1alpha4.InventoryList).ListMeta}
	for _, item := range obj.(*v1alpha4.InventoryList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested inventories.
func (c *FakeInventories) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(inventoriesResource, c.ns, opts))

}

// Create takes the representation of a inventory and creates it.  Returns the server's representation of the inventory, and an error, if there is any.
func (c *FakeInventories) Create(ctx context.Context, inventory *v1alpha4.Inventory, opts v1.CreateOptions) (result *v1alpha4.Inventory, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(inventoriesResource, c.ns, inventory), &v1alpha4.Inventory{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.Inventory), err
}

// Update takes the representation of a inventory and updates it. Returns the server's representation of the inventory, and an error, if there is any.
func (c *FakeInventories) Update(ctx context.Context, inventory *v1alpha4.Inventory, opts v1.UpdateOptions) (result *v1alpha4.Inventory, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(inventoriesResource, c.ns, inventory), &v1alpha4.Inventory{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.Inventory), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeInventories) UpdateStatus(ctx context.Context, inventory *v1alpha4.Inventory, opts v1.UpdateOptions) (*v1alpha4.Inventory, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(inventoriesResource, "status", c.ns, inventory), &v1alpha4.Inventory{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.Inventory), err
}

// Delete takes name of the inventory and deletes it. Returns an error if one occurs.
func (c *FakeInventories) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(inventoriesResource, c.ns, name, opts), &v1alpha4.Inventory{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeInventories) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(inventoriesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha4.InventoryList{})
	return err
}

// Patch applies the patch and returns the patched inventory.
func (c *FakeInventories) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha4.Inventory, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(inventoriesResource, c.ns, name, pt, data, subresources...), &v1alpha4.Inventory{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.Inventory), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied inventory.
func (c *FakeInventories) Apply(ctx context.Context, inventory *metalv1alpha4.InventoryApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha4.Inventory, err error) {
	if inventory == nil {
		return nil, fmt.Errorf("inventory provided to Apply must not be nil")
	}
	data, err := json.Marshal(inventory)
	if err != nil {
		return nil, err
	}
	name := inventory.Name
	if name == nil {
		return nil, fmt.Errorf("inventory.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(inventoriesResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha4.Inventory{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.Inventory), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeInventories) ApplyStatus(ctx context.Context, inventory *metalv1alpha4.InventoryApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha4.Inventory, err error) {
	if inventory == nil {
		return nil, fmt.Errorf("inventory provided to Apply must not be nil")
	}
	data, err := json.Marshal(inventory)
	if err != nil {
		return nil, err
	}
	name := inventory.Name
	if name == nil {
		return nil, fmt.Errorf("inventory.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(inventoriesResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha4.Inventory{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha4.Inventory), err
}
