name: Tests

on:
  pull_request:
    types:
      - opened
      - edited
      - assigned
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '**/*.md'
    branches:
      - main

jobs:
  lint:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Configure git for private modules
        run: git config --global url."https://${{ secrets.GIT_USER }}:${{ secrets.GIT_PASSWORD }}@github.com".insteadOf "https://github.com"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42
  tests:
    needs: lint
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Configure git for private modules
        run: git config --global url."https://${{ secrets.GIT_USER }}:${{ secrets.GIT_PASSWORD }}@github.com".insteadOf "https://github.com"

      - name: run tests
        run: make test
