name: Pull Request Code test

on:
  pull_request_target:
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  checks:
    name: run
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - run: |
          ./hack/setup-git-redirect.sh
          mkdir -p ~/.ssh
          ssh-keygen -R github.com
          curl -L https://api.github.com/meta | jq -r '.ssh_keys | .[]' | sed -e 's/^/github.com /' >> ~/.ssh/known_hosts
      - run: make build
      - run: make test
