name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go-tests:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        run: make test

  go-lint:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42

  helm-lint:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - uses: azure/setup-helm@v1
        with:
          version: 'v3.6.2'

      - name: Lint Helm
        run: |
          helm lint chart --strict