name: Tests

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '**/*.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '**/*.md'
    branches:
      - main

jobs:
  go-tests:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Configure git for private modules
        run: git config --global url."https://${{ secrets.GIT_USER }}:${{ secrets.GIT_PASSWORD }}@github.com".insteadOf "https://github.com"

      - name: Test
        run: make test
